### ISSUE TITLE
GPM issues

### ISSUE THREAD

**Issue by w00fz** [mautic/mautic-grav#12]
Hey there,

I was forced to remove `mautic-grav` from the GPM because I noticed it failing during blueprint parse. I also noticed other non-standard takes in the repository and I just wanted to point them out to you so that they can be corrected and I can add the plugin back in GPM.

1. The main issue is in the blueprint: https://github.com/mautic/mautic-grav/blob/main/blueprints.yaml#L38-L40
    This is not proper YAML. That should be all kept in 1 line. Alternatively, multiline should be handled differently, ie:
    ```yaml
     help: > 
       If enabled, tracking code is injected in every page on load; If
       disabled, no tracking code is injected, which is useful if you want to
       control tracking from within a consent manager (to conform to the GDPR)
    ```
    https://yaml-multiline.info/
2. Your repository tags are not consistent, this is mostly on our part but I noticed you started with tag `1.1.2` and ended up with tag `v1.3.2`. I believe this is ok right now but I would suggest picking one format and sticking to it, our GPM generator is going to potentially get confused when comparing strings to determine the order and you might experience unexpected results where `1.1.2` is considered the latest release. If this is going to be the case, your fix would be to rename the `1.1.2` tag to `v1.1.2` and going forward always prefix your tags with `v`.
3. Your [CHANGELOG.md](https://github.com/mautic/mautic-grav/blob/main/CHANGELOG.md) is backward. This is a convention in Grav where we always keep the latest versions at the top. It does make things more efficient because we don't have to parse the entire file and reach to the end to get the current changelog set. As developer you will also find this much easier to maintain as everything is there in view when you go editing the file. I would suggest you invert the order and going forward you always keep everything at the top.

I hope this helps and I hope to see the changes done soon so that I can re-enable the plugin.

Thank you.

**Comment by escopecz** [comment]
Thank you @w00fz for very detailed informations on how to fix and improve the plugin! 

@christian-krieg do you think you could look into this?

We could use https://github.com/nrkno/yaml-schema-validator-github-action or other options out there to validate yaml files in GH Actions to get notified about this before merging and releasing. What do you think?

**Comment by christian-krieg** [comment]
Thanks a lot @w00fz for your detailed audit.

I already wondered about why the plugin suddently stopped showing up in GPM, and I feared I messed something up with my recent releases. I am pretty new to the Grav ecosystem, so I hope you can forgive my early infantility.

@escopecz I guess fixing the issues is straight-forward, so I definitely can look into this (by end of the week latest). I am also very open regarding the long-term validation strategy you propose! However, I am not yet familiar with GH Actions, but willing to learn.

**Comment by RCheesley** [comment]
Sounds good to use the action so that we snag any potential issues before they go out! Thanks for looking into it and thanks @w00fz for reporting the issue!

Happy to help with the actions side of things if needed!

**Comment by christian-krieg** [comment]
Just to make sure in advance: Do you have a preferred method of re-naming the tags? I would follow the approach as described here:

[https://stackoverflow.com/a/5719854](url)

Would that be in line with this project's policies?

Also, how shall we name the tags? GitHub suggests to prefix release tags with "v"; on the other hand, this project started to name tags without a "v" prefix. Do you think it's a good idea to rename all tags to have a prefix, or should we stick to the initial naming scheme without "v"?

**Comment by RCheesley** [comment]
I would suggest keeping it simple - we just use the version number in mautic/mautic: https://github.com/mautic/mautic/tags using semantic versioning etc.

**Comment by christian-krieg** [comment]
Perfect, thanks a lot!

**Comment by christian-krieg** [comment]
@escopecz @dongilbert @RCheesley I just fixed the tag names, could you please remove the deleted tags by running the following command:

```
git pull --prune --tags
```

Thx!

**Comment by christian-krieg** [comment]
Issues should be fixed in #13; Thanks again @w00fz for providing the solutions along with the problem!

**Comment by w00fz** [comment]
Hey, no problem at all.

One other thing in the blueprints.yaml is the `version:` property, you probably want that up to date with your actual release version (ie, `version: 1.3.2`) and update it on every release.

https://github.com/mautic/mautic-grav/blob/main/blueprints.yaml#L2

Everything else looks good now. Once you have a new release out I can test-run it for you. In the future we have plans to have better automated tools that will tell you everything that is wrong as you try to release. This unfortunately takes time and it might happen on a version 2 of GPM.

**Comment by christian-krieg** [comment]
@w00fz thanks a lot for the hint! I was already wondering why the version didn't change with the release, assuming that GPM automatically takes the most recent version from the CHANGELOG :)

@escopecz I had a look at https://github.com/nrkno/yaml-schema-validator-github-action; If there is a schema definition provided by Grav I guess we would be ready to go; Otherwise, I fear I don't have the resources to follow up on this as it would require to define a YAML scheme for arbitrary input (as far as I can tell from a quick look).

Probably I'm missing something important here, but from my current point of view, manual review would be the most efficient option to validate the YAML files associated with this plugin.

**Comment by christian-krieg** [comment]
@w00fz finally there is a release fixing the issues you pointed out:
https://github.com/mautic/mautic-grav/releases/tag/1.4.0

Could you please test if it complies with GPM now?

Thank you so much in advance!

**Comment by w00fz** [comment]
I tested and everything is looking great now. I added it back to GPM which has already picked the plugin up. 👍 

Cheers,

**Comment by christian-krieg** [comment]
Cool, thanks a lot! 🥳
