### ISSUE TITLE
Missing JS tag in v1.1.0

### ISSUE THREAD

**Issue by bmalynovytch** [mautic/mautic-grav#4]
A regression was introduced in v1.1.0 when adding the JS tag in place of the pixel tag.

**Comment by christian-krieg** [comment]
Hi @bmalynovytch, if still relevant for you, could you please check if the plugin now behaves as expected? Thanks a lot in advance!

**Comment by christian-krieg** [comment]
As this issue seems outdated, I'll close it for now. In case it is still relevant, please feel free to re-open!
