### ISSUE TITLE
Tracking pixel used instead of JS tracking

### ISSUE THREAD

**Issue by pericazivkovic** [mautic/mautic-grav#6]
After enabling the plugin, it shows tracking pixel in header, not JS tracking

**Comment by christian-krieg** [comment]
Hi @pericazivkovic if still relevant for you, could you please check if the plugin now behaves as expected?

**Comment by christian-krieg** [comment]
As this issue seems outdated, I'll close it for now. In case it is still relevant, please feel free to re-open!
