### ISSUE TITLE
plugin not working 

### ISSUE THREAD

**Issue by JOduMonT** [mautic/mautic-grav#7]
Hi start played with Mautic a year ago
Now switching to Grav I discover this plugin
The installation seams simple
but after all I don't see any Mautic line in my website code (I'm looking for mau or/and autic).

### On my Grav
- JavaScript pipeline is disabled

When I active the **debugger** the only place it mention mautic is under Plugins :

mautic
array:2 [
  "enabled" => true
  "url" => "https://j****t.mautic.net"
]

So I'm a little bit confuse about what i'm doing wrong and how to fix it

Also might be obvious but
If I include [plugin:mautic](13) in a default page I have this error :
 TypeError
Argument 1 passed to DOMLettersIterator::__construct() must be an instance of DOMNode, null given, called in `/var/www/j*****t/system/src/Grav/Common/Helpers/Truncator.php` on line 108 which 
`        $letters = new DOMLettersIterator($body);`

**Comment by christian-krieg** [comment]
Hi @JOduMonT if still relevant for you, could you please test if the plugin is working as expected? There has been some activity it the near past to fix this plugin, so maybe now it works as you expect?

**Comment by christian-krieg** [comment]
As this issue seems outdated, I'll close it for now. In case it is still relevant, please feel free to re-open!
